MODEL:
  META_ARCHITECTURE : "convnext_small_in22ft1k"
  SEGMENTATION_HEAD : "fpn"
  EMA : 0.0
LOSS:
  NAME : "crossentropy"
SOLVER:
  IMS_PER_BATCH : 16
  BASE_LR  : 0.0002
  EPOCH : 50
  WEIGHT_DECAY : 1e-2
  WARMUP_EPOCH : 0
  LR_SCHEDULER : 'cos'
  OPTIMIZER : "ADAMW"
  GRADIENT_CLIP : 0.0
  ACCUMULATION : 1
DATASETS:
  IMAGE_SIZE : 256
  LABEL_SMOOTHING : 0.1
  CUTMIX : 0.0
  HALFCUTMIX : 0.0
  VAL : 0
DATALOADER:
  WORKERS : 64
DISTRIBUTE:
  DISTRIBUTE : False
  MULTIPROCESSING_DISTRIBUTE : False
  WORLD_SIZE : 1
  DIST_URL : "tcp://localhost:10001"
  DIST_BACKEND : "nccl"
  GPU : 0
  RANK : 0
ETC :
  WANDB : True
  EVAL : False
  CHANNELS_LAST : False
  AMP : False
  TTA : False
  SWEEP : True