MODEL:
  META_ARCHITECTURE : "swin_base"
  SEGMENTATION_HEAD : "lawin"
  EMA : 0.0
SOLVER:
  IMS_PER_BATCH : 64
  BASE_LR  : 0.0002
  EPOCH : 2
  WEIGHT_DECAY : 1e-2
  WARMUP_EPOCH : 0
  LR_SCHEDULER : 'cos'
  OPTIMIZER : "ADAMW"
  GRADIENT_CLIP : 0.0
  ACCUMULATION : 1
DATASETS:
  IMAGE_SIZE : 256
  LABEL_SMOOTHING : 0.1
DATALOADER:
  WORKERS : 32
DISTRIBUTE:
  DISTRIBUTE : False
  MULTIPROCESSING_DISTRIBUTE : True
  WORLD_SIZE : 1
  DIST_URL : "tcp://localhost:10001"
  DIST_BACKEND : "nccl"
  GPU : 0
  RANK : 0
ETC :
  WANDB : False
  EVAL : False
  CHANNELS_LAST : False
  AMP : False