MODEL:
  META_ARCHITECTURE : "convnext"
  EMA : 0.0
SOLVER:
  IMS_PER_BATCH : 128
  BASE_LR  : 0.0002
  EPOCH : 200
  WEIGHT_DECAY : 1e-2
  WARMUP_EPOCH : 0
  LR_SCHEDULER : 'cos'
  OPTIMIZER : "ADAMW"
  GRADIENT_CLIP : 0.0
  ACCUMULATION : 0
DATASETS:
  IMAGE_SIZE : 256
  LABEL_SMOOTHING : 0.0
DATALOADER:
  WORKERS : 32
DISTRIBUTE:
  DISTRIBUTE : False
  MULTIPROCESSING_DISTRIBUTE : True
  WORLD_SIZE : 1
  DIST_URL : "tcp://localhost:10001"
  DIST_BACKEND : "nccl"
  GPU : 0
  RANK : 0
ETC :
  WANDB : True
  EVAL : False
  CHANNELS_LAST : False
  AMP : False